# version: 0.2

# env:
#   variables:
#     S3_KEY: function.zip
#     S3_BUCKET_NAME: cicd-python-bkt

# phases:
#   install:
#     runtime-versions:
#       python: 3.11
#     commands:
#       - pip install --upgrade pip

#   build:
#     commands:
#       - echo "Zipping Lambda function..."
#       - zip -r $S3_KEY lambda/
#       - echo "Uploading to S3..."
#       - aws s3 cp $S3_KEY s3://$S3_BUCKET_NAME/$S3_KEY

# artifacts:
#   files:
#     - template.yaml
#     - function.zip



version: 0.2

env:
  variables:
    S3_KEY: function.zip
    S3_BUCKET_NAME: cicd-python-bkt

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install --upgrade pip

  build:
    commands:
      - echo "Zipping Lambda function..."
      - zip -r $S3_KEY lambda/
      - echo "Uploading to S3..."
      - aws s3 cp $S3_KEY s3://$S3_BUCKET_NAME/$S3_KEY

artifacts:
  files:
    - template.yaml
    - function.zip
